openapi: 3.0.2
info:
  title: 'FSTR API'
  description: ''
  version: '1'
paths:
  /api/pereval/:
    get:
      summary: Все перевалы
      description: 'Возвращает список перевалов. Который можно посмотреть на странице http://127.0.0.1:8000/api/pereval/'
      operationId: listpereval
      parameters: []
      responses:
        '200':
          description: 'успешно'
          content:
            application/json:
              schema:
                title: successfully
                type: object
                properties:
                  placeholder:
                    type: string

      tags:
        - pereval
    post:
      summary:  Создание нового перевала
      operationId: createpereval
      description: 'Создает новый перевал'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pereval'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/pereval'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/pereval'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pereval'
        '405':
          description: Invalid input
        '400':
          description: Bad Request
      tags:
        - pereval
  /api/pereval/{id}/:
    get:
      summary:  Получение одного перевала по id
      operationId: retrievePereval
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальное целочисленное значение, идентифицирующее этот перевал.
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pereval'
          description: ''
      tags:
        - pereval
    put:
      operationId: updatePereval
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this pereval.
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pereval'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/pereval'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/pereval'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pereval'
          description: ''
      tags:
        - pereval
    patch:
      summary:  Изменение перевала
      operationId: partialUpdatePereval
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this pereval.
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pereval'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/pereval'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/pereval'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pereval'
          description: ''
      tags:
        - pereval
components:
  schemas:
    pereval:
      type: object
      title: pereval
      description: Перевал
      properties:
        id:
          type: integer
          format: int64
          description: Уникальное целое число, определяющее этот перевал
          readOnly: true
        beautyTitle:
          type: string
          description: beautyTitle
          maxLength: 7
        title:
          type: string
          description: Название перевала
          maxLength: 150
        other_titles:
          type: string
          description: Дополнительные названия
          maxLength: 150
        connect:
          type: string
          format: text
          description: соединяет
        level:
          $ref: '#/components/schemas/Level'
        images:
          $ref: '#/components/schemas/Images'
        add_time:
          type: string
          format: timezone
          description: Дата и время добавления
          readOnly: true
        coords:
          $ref: '#/components/schemas/Coords'
        user:
          $ref: '#/components/schemas/Users'
        status:
          type: string
          enum:
              - new
              - pending
              - accepted
              - rejected
          default: new
          maxLength: 8
          description: 'Статус модерации. Допустимые значения: "new", "pending", "accepted", "rejected"'

    Users:
      type: object
      title: Users
      description: Пользователь
      properties:
        email:
          type: string
          format: email
          maxLength: 128
          description: Адрес электронной почты
        fam:
          type: string
          maxLength: 30
          example: Иванов
          description: Фамилия
        name:
          type: string
          maxLength: 30
          example: Иван
          description: Имя
        otc:
          type: string
          maxLength: 30
          example: Иваныч
          description: Отчество
        phone:
          type: string
          minLength: 11
          maxLength: 12
          example: 88002000500
          description: Номер телефона

    Coords:
      type: object
      title: Coords
      description: Координаты
      properties:
        latitude:
          type: number
          format: float
          maxLength: 9
          example: 75.123456
          description: Широта
        longitude:
          type: number
          format: float
          maxLength: 9
          example: 75,123456
          description: Долгота
        height:
          type: integer
          maxLength: 5
          example: 12345
          description: Высота


    Level:
      type: string
      enum:
        - 1A
        - 1B
        - 2A
        - 2B
        - 3A
        - 3B

    Images:
      type: object
      title: Images
      description: Фотографии перевала
      properties:
        title:
          type: string
          description: Название
          maxLength: 50
        data:
          type: string
          format: url
          description: Ссылка на фотографию

    '200':
      description: 'успешно'
