# Generated by Django 4.2.7 on 2023-11-19 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=128)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.TextField(blank=True, null=True, verbose_name='Зима')),
                ('spring', models.TextField(blank=True, null=True, verbose_name='Весна')),
                ('summer', models.TextField(blank=True, null=True, verbose_name='Лето')),
                ('autumn', models.TextField(blank=True, null=True, verbose_name='Осень')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField(max_length=255, verbose_name='Контактный телефон')),
                ('first_name', models.TextField(max_length=255, verbose_name='Имя')),
                ('last_name', models.TextField(max_length=255, verbose_name='Фамилия')),
                ('surname', models.TextField(max_length=255, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('new', 'новый'), ('pending', 'в работе'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='new')),
                ('beauty_title', models.TextField(blank=True, null=True, verbose_name='Основное название вершины')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Название вершины')),
                ('other_titles', models.TextField(blank=True, null=True, verbose_name='Другое название')),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.TimeField(auto_now_add=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fstr.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.users')),
            ],
        ),
    ]
